- set_fact:
    swap_file_path: /swapfile
# args creates でファイルが存在しなければ実行させるという動き
- shell: dd if=/dev/zero of={{ swap_file_path }} bs={{ ansible_memtotal_mb * 2 }} count=1M
  args:
    creates: '{{ swap_file_path }}'
- file:
    path: '{{ swap_file_path }}'
    mode: '0600'
- shell: file {{ swap_file_path }}
  register: swap_file_test
- shell: mkswap {{ swap_file_path }}
  when: swap_file_test.stdout.find('swap file') == -1
- shell: swapon {{ swap_file_path }}
  when: ansible_swaptotal_mb < 1
- name: fstab編集
  lineinfile: dest=/etc/fstab line="/swapfile swap swap defaults 0 0"
#- mount:
#    name: swap
#    src: '{{ swap_file_path }}'
#    fstype: swap
#    opts: defaults
#    passno: '0'
#    dump: '0'
#    state: present
